Bom updates and Readme update
google-developer-training/basic-android-kotlin-compose-training-mars-photos pull request #33
Opened 2023-02-11 00:53 UTC by android-dev-lxl

2023-02-13 20:47 UTC, johnshea commented on app/build.gradle
> +    implementation "com.google.android.material:material:1.8.0"
Please check if we need this dependency and remove if not needed.

2023-02-22 17:54 UTC, yenerm requested changes

2023-02-22 17:54 UTC, yenerm commented on app/build.gradle
> +
can't comment on the right line but the following should be updated too:

id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.10'

2023-02-22 19:30 UTC, yenerm approved these changes

2023-02-22 20:14 UTC, osuleymanova approved these changes

2023-02-22 20:15 UTC, merged