E2E Starter branch
google-developer-training/basic-android-kotlin-compose-training-mars-photos pull request #81
Opened 2023-08-23 04:32 UTC by android-dev-lxl

2023-08-30 22:01 UTC, johnshea reviewed
MainActivity.kt - Is this call still needed `WindowCompat.setDecorFitsSystemWindows(window, false)`? It is part of the e2e code in `Theme.kt` and appears to be redundant.

2023-09-06 01:17 UTC, android-dev-lxl commented on app/src/main/java/com/example/marsphotos/ui/screens/HomeScreen.kt
> +    contentPadding: PaddingValues = PaddingValues(0.dp),
https://github.com/google-developer-training/basic-android-kotlin-compose-training-mars-photos/pull/83#discussion_r1310960047

2023-09-19 16:06 UTC, johnshea requested changes
There is an issue with how the UI for e2e is done. In starter_e2e, the surface is running under the topappbar which is not happening in branch starter.

Note - I added additional Text composables to check this.
<img width="500" alt="Screenshot 2023-09-19 at 11 59 12 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-mars-photos/assets/7107817/f1424460-5605-49e6-86eb-c87c17358d63">

<img width="500" alt="Screenshot 2023-09-19 at 11 56 37 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-mars-photos/assets/7107817/45f3b5fb-62f1-4962-a51f-973fe233faf8">
<img width="1155" alt="Screenshot 2023-09-19 at 12 05 01 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-mars-photos/assets/7107817/dbd74f9c-5e1e-4a07-8ac8-b7d4abf29c3f">

2023-09-25 15:41 UTC, johnshea approved these changes
lgtm

2023-10-20 18:54 UTC, johnshea approved these changes
lgtm

2024-02-01 20:35 UTC, merged